OBJS_MODULE_SRC = ./src/parameter.o \
		  ./src/namelist.o \
		  ./src/com_var.o \
		  ./src/var.o \
		  ./src/grads.o \


OBJS_SRC = ./src/isen_cold_air.o \
	   ./src/time.o \
	   ./src/undef.o \
	   ./src/check_range.o \
	   ./src/calc_pt.o \
	   ./src/pt_ground.o \
	   ./src/convert.o \
	   ./src/calc_dp.o \
	   ./src/calc_dpflux.o \
	   ./src/calc_divergence.o \
	   ./src/calc_nhc.o \
	   ./src/time_derivative.o \
